# Get mock data from fake server
GET http://localhost:3123/api HTTP/1.1

###
HEAD /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###
GET /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###
POST /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
Content-Type: application/json
Content-Length: 88

{
    "title": "Новая публикация",
    "body": "Текст публикации",
    "userId": 31337
}
###
GET /secret-page HTTP/1.1
Host: myserver.local
Authorization: Basic YWRtaW46MTIzNDU2
